# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S7Ma6RSWQjXjYQxE_ajFVHVk97zjDZ2U
"""

from google.colab import files

uploaded = files.upload()

filename = list(uploaded.keys())[0]

with open(filename, "r", encoding="utf-8") as file:
    document_text = file.read()

print("✅ Document Loaded Successfully")
print("\nDocument Preview:\n")
print(document_text)

# Chat History
chat_history = []

while True:

    question = input("\nAsk a question about the document (type 'exit' to quit): ")

    if question.lower() == "exit":
        print("Chat Ended!")
        break

    print("\nMulti-step Reasoning")
    print("Step 1: Understanding the question...")
    print("Step 2: Searching the document...")
    print("Step 3: Finding the answer...\n")

    answer = "Sorry, I could not find the answer."

    # Search document
    for line in document_text.split("\n"):

        if question.lower() in line.lower():

            answer = line
            break

    print("Answer:")
    print(answer)

    # Save conversation
    chat_history.append(("User", question))
    chat_history.append(("Assistant", answer))

topic = input("Enter a topic to search: ")

print("\n========== Web Search Results ==========\n")

web_results = [
    f"Wikipedia - {topic}",
    f"GeeksforGeeks - {topic}",
    f"IBM - {topic}",
    f"Microsoft Learn - {topic}",
    f"Google Scholar - {topic}"
]

for i, result in enumerate(web_results, start=1):
    print(f"{i}. {result}")

print("\n✅ Web Search Completed")

note = input("Write your research note:\n")

with open("research_notes.txt", "a") as file:
    file.write(note + "\n")

print("✅ Research Note Saved Successfully")

print("\n========== Conversation History ==========\n")

if len(chat_history) == 0:
    print("No conversation available.")

else:
    for role, message in chat_history:
        print(role + ":", message)